name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt-get update && \
            DEBIAN_FRONTEND=noninteractive apt-get install -y \
            git curl \
            clang make lldb \
            libpcre2-dev libreadline-dev
      - run: make
